### ISSUE TITLE
Add a function to interpolates data on a curvilinear grid to an unstructured grid

### ISSUE THREAD

**Issue by weathor** [NCAR/wrf-python#104]
Is there an rcm2points function similar to NCL in existing wrf-python? There doesn't seem to be a function that interpolates wrfout to a lat/lon station in wrf-python's interpolation function.

**Comment by clyne** [comment]
rcm2points has just be ported from NCL to GeoCAT.comp:

https://geocat-comp.readthedocs.io/en/latest/

I'm not sure if it is available in the current conda installer. @khallock can confirm.

**Comment by weathor** [comment]
Hi,
Thanks for your response.
GeoCAT.comp works fine on my machine's conda environment.
regrads,
Li Hongbing

在2020-01-10 11:02:43，clynenotifications@github.com写道：

rcm2points has just be ported from NCL to GeoCAT.comp:

https://geocat-comp.readthedocs.io/en/latest/

I'm not sure if it is available in the current conda installer. @khallock can confirm.

**Comment by clyne** [comment]
Glad to hear it!

> On Jan 10, 2020, at 12:08 AM, lihb <notifications@github.com> wrote:
> 
> Hi,
> Thanks for your response.
> GeoCAT.comp works fine on my machine's conda environment.
> regrads,
> Li Hongbing
> 
> 在2020-01-10 11:02:43，clynenotifications@github.com写道：
> 
> rcm2points has just be ported from NCL to GeoCAT.comp:
> 
> https://geocat-comp.readthedocs.io/en/latest/
> 
> I'm not sure if it is available in the current conda installer. @khallock can confirm.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu
