### ISSUE TITLE
WrfPyApp

### ISSUE THREAD

**Issue by onurhdogan** [NCAR/wrf-python#107]
I have published WrfPyApp gui application on https://github.com/onurhdogan/WrfPyApp/blob/master/README.md .
It uses WrfPython package and supports investigate the Data quickly.
I am open to criticism and suggestions for the developing in next version. 
Tutorial video is via https://www.youtube.com/watch?v=OOU85-5CM5w. 

Thank You

**Comment by clyne** [comment]
Very cool! Thanks for sharing.
