### ISSUE TITLE
"nan" values in interplevel 

### ISSUE THREAD

**Issue by Neeldip** [NCAR/wrf-python#108]
I am trying to get the wind speed from a wrf file at a certain level. Except a few elements in the array, all other values are 'nan'

```
import netCDF4 as nc
import wrf as w
import numpy as np

wrf = nc.Dataset("G:\wrfout_d03_2018-03-31_01%3A00%3A00.nc")
lat = w.getvar(wrf,'XLAT')
lon = w.getvar(wrf,'XLONG')

#print(lat,lon)
#print(type(lat))
for timeidx in range(0,1,1):
    U = w.getvar(wrf,'ua', timeidx)
    V = w.getvar(wrf,'va', timeidx)
    SPD = U**2+V**2
    SPD = np.sqrt(SPD)
    PHB = w.getvar(wrf,"PHB", timeidx)
    PH = w.getvar(wrf,"PH", timeidx)
    P1 = w.destagger(PHB, stagger_dim=0, meta=True)
    P2 = w.destagger(PH, stagger_dim=0, meta=True)
    P = (P1+P2)/9.81
    SPD = w.interplevel(field3d=SPD, vert=P, desiredlev=80)
    SPD = SPD.rename({'south_north':'latitude','west_east':"longitude"})
    print(SPD)
```

**Comment by ewquon** [comment]
I also have this problem. I have verified that this occurs independent of system (mac, linux) and whether the input data are numpy arrays, xarray DataArray, or netcdf Dataset.

**Comment by michaelavs** [comment]
@ewquon 
I'm currently looking through the [source code for interplevel](https://github.com/NCAR/wrf-python/blob/develop/src/wrf/interp.py) to see if I can find what may be causing the return of NaN values. Would you mind adding a code excerpt here so I can better trace things on my side? Something that may also be helpful is the shape/length of your input values (which it seems you have already checked, but it could be helpful for my side of researching this issue). Generally, NaN is returned for values that either shouldn't exist (e.g. negative height values) or just don't exist (e.g missing data points from the wrfout file). When it comes to the "shouldn't exist" side, this sometimes it resolved with changing declared boundaries or levels. When it comes to the "doesn't exist" side, this sometimes is a problem with the actual wrf simulation and/or a mismatch in data points to interpolate(as in there are 25 points for one value and only 10 for the other). 

As a double check, I also wanted to make sure you have seen/used the examples on the [wrf-python website](https://wrf-python.readthedocs.io/en/latest/plot.html), specifically the example under "Horizontal interpolation to a pressure level". This resource may indicate if you have an error in how you have read in and used the data. No worries if you have already looked through and tried this method, or if it won't work with what you are trying to do, I just want to make sure you have all available resources that may help resolve this issue!

**Comment by ewquon** [comment]
Hi @michaelavs, thank you for the very quick response. I'm a bit embarrassed to say that one of the conditions that I had previously asserted--that the requested levels are within the data range--is actually untrue. I had neglected to account for the surface elevation in my input values. So my results are actually consistent with the discussion in #120, which indicate that NaNs will appear if the interpolation points are out of range. Sorry for the trouble.
