### ISSUE TITLE
Cannot use the "from wrf import getvar, latlon_coords, ALL_TIMES"

### ISSUE THREAD

**Issue by wk-atmchem** [NCAR/wrf-python#111]
I'm new to Python. I'm trying in import random words from words. I'm facing this issue. Help me out anyone.

Traceback (most recent call last):

  File "C:\Users\wukai\OneDrive\desktop\pythonscripts\wrf.py", line 14, in <module>
    from wrf import getvar, latlon_coords, ALL_TIMES

  File "C:\Users\wukai\OneDrive\desktop\pythonscripts\wrf.py", line 14, in <module>
    from wrf import getvar, latlon_coords, ALL_TIMES

ImportError: cannot import name 'getvar'

And I have checked that I installed the wrf-python successfully.

**Comment by jthielen** [comment]
It looks like the file you are running this from is `wrf.py`, which may cause a name conflict with the `wrf-python` module named `wrf`. Have you tried running the same import statement from a REPL prompt (such as you get when you run `python` or `ipython`) in a different directory/folder or script with another name?

**Comment by wk-atmchem** [comment]
Hi Thielen,
   I tried to rename the script to processwrf.py and now it works well. Thanks!
   BTW, nice to meet you!

**Comment by jthielen** [comment]
Glad to hear that helped!
