### ISSUE TITLE
get_slp issues

### ISSUE THREAD

**Issue by allenea** [NCAR/wrf-python#116]
This command should return slp data for all time-steps. But this will just run forever memory will continue to pile on. It makes a simple program take up over 13GB of memory. Something is messed up. 

python version : 3.7.6.final.0
wrf-python                1.3.2            py37h2cdb68b_1    conda-forge

wrf.g_slp.get_slp(wrf_data.ncfile, timeidx=wrf.ALL_TIMES,\
                                        method='cat', squeeze=True, cache=None,\
                                        meta=False, _key=None, units='Pa')

This works:
wrf.g_slp.get_slp(wrf_data.ncfile, timeidx=42,\
                                        method='cat', squeeze=True, cache=None,\
                                        meta=False, _key=None, units='Pa')
Out[11]: 
array([[100578.61 , 100579.12 , 100581.39 , ..., 100936.125, 100938.6  ,
        100935.53 ],
       [100578.28 , 100576.94 , 100579.29 , ..., 100932.375, 100935.05 ,
        100934.28 ],
       [100571.41 , 100575.17 , 100576.75 , ..., 100932.1  , 100933.84 ,
        100933.04 ],
       ...,
       [100099.49 , 100088.87 , 100080.65 , ..., 100777.836, 100779.914,
        100780.84 ],
       [100085.53 , 100086.65 , 100087.484, ..., 100775.734, 100777.484,
        100780.07 ],
       [100089.5  , 100090.71 , 100071.734, ..., 100775.32 , 100777.1  ,
        100778.78 ]], dtype=float32)

Additionally:
Does not work:
data = wrf.getvar(wrf_data.ncfile, "slp", timeidx=wrf.ALL_TIMES,\
                  method='cat', squeeze=True, cache=None,\
                            meta=False, units="Pa")

Works without the time dimension for one time step (not specified, I assume the first index)
data = wrf.getvar(wrf_data.ncfile, "slp",\
                  method='cat', squeeze=True, cache=None,\
                            meta=False, units="Pa")

data = wrf.getvar(wrf_data.ncfile, "slp",\
                  method='cat', squeeze=True, cache=None, units="Pa")

data
Out[39]: 
<xarray.DataArray 'slp' (south_north: 396, west_east: 426)>
array([[101804.4  , 101806.67 , 101803.164, ..., 101820.13 , 101820.125,
        101820.09 ],
       [101806.55 , 101809.52 , 101804.06 , ..., 101819.766, 101819.766,
        101819.695],
       [101807.54 , 101807.695, 101805.02 , ..., 101819.4  , 101819.34 ,
        101819.32 ],
       ...,
       [101458.836, 101451.05 , 101467.63 , ..., 101544.85 , 101545.19 ,
        101545.56 ],
       [101472.125, 101453.03 , 101451.57 , ..., 101544.016, 101544.33 ,
        101544.734],
       [101487.91 , 101461.48 , 101441.25 , ..., 101543.18 , 101543.516,
        101543.875]], dtype=float32)
Coordinates:
    XLONG    (south_north, west_east) float32 -77.836426 ... -72.93207
    XLAT     (south_north, west_east) float32 36.876892 36.87711 ... 40.42288
    XTIME    float32 0.0
    Time     datetime64[ns] 2014-06-03T12:00:00
Dimensions without coordinates: south_north, west_east
Attributes:
    FieldType:    104
    MemoryOrder:  XY
    description:  sea level pressure
    units:        Pa
    stagger:      
    coordinates:  XLONG XLAT XTIME
    projection:   LambertConformal(stand_lon=-75.56600189208984, moad_cen_lat...

WRF-Python does not appear to have a true working diagnostic variable for SLP. P (level = 0) =/= SLP

**Comment by michaelavs** [comment]
Hi @allenea, 
I'm sorry I did not respond to this issue when it was first posted! Have you been able to find a solution to this error? If so, would you be able to post what resolved the issue? If not, and if you would like to continue troubleshooting the problem, could you please provide the import statements and code that you were using to get to this point? I'm mostly interested in the code that has gotten you closest to the result you expected and, if possible, the code that should have gotten you the expected result (assuming that code isn't working). It would appear that there are many time indexes in your wrfout file which is causing the large memory usage when ```timeidx=wrf.ALL_TIMES``` but not when you have timeidx set to a specific index or the default of index=0. It looks like you may also be able to find information on this issue (and how to resolve it) on the WRF-python website: https://wrf-python.readthedocs.io/en/latest/basic_usage.html?highlight=timeidx#memory-issues-with-wrf-all-times.

If I don't hear back from you by next Tuesday (3/23), I will mark this issue as resolved and close it.

**Comment by allenea** [comment]
Hi @michaelavs I did not see this response until now. Marking it closed is fine. However, I am pretty sure there is a memory leak somewhere related to that function. I never got it solved and honestly I forget which code I was using this on... I believe that it might have been cross section plots.
