### ISSUE TITLE
Variable T2 is used in example, but not listed in table of available diagnostics

### ISSUE THREAD

**Issue by irowebbn** [NCAR/wrf-python#122]
WRF Output variable T2 is used in an example with `getvar` [here](https://wrf-python.readthedocs.io/en/latest/basic_usage.html#id1)

```python
from netCDF4 import Dataset
from wrf import getvar, interpline, CoordPair

ncfile = Dataset("wrfout_d01_2016-10-07_00_00_00")

# Get the 2m temperature
t2 = getvar(ncfile, "T2")
```

But it is not listed in the table [here](https://wrf-python.readthedocs.io/en/latest/user_api/generated/wrf.getvar.html#wrf.getvar).

**Comment by irowebbn** [comment]
I don't know how the documentation is structured, but I am willing to make a pull request that adds that entry to the table using the information from the WRF User manual.

**Comment by clyne** [comment]
That would be much appreciated! Please let us know if you need guidance.
