### ISSUE TITLE
How to extract a time series csv (time,var) for a single lat/lon coord pair

### ISSUE THREAD

**Issue by fjime** [NCAR/wrf-python#129]
HI everyone and thanks for all the support, Im new on wrf-python.

from netCDF4 import Dataset
from wrf import (getvar, xy_to_ll, ALL_TIMES)
file_paths = ["wrfout_d01_2005-08-28_00_00_00", "wrfout_d01_2005-08-28_12_00_00"]
wrf_files = [Dataset(file_paths[0]), Dataset(file_paths[1])]
lat_lon = xy_to_ll(wrf_files, 12, 11)
T = getvar(wrf_files, "T2", timeidx=ALL_TIMES, method="cat")
print(T)

I already cat the 2 files and got the temperature array, but i dont know how to configure using getvar or other tools to get a time_series, for a single lat/lon and T2 at all times.

**Comment by michaelavs** [comment]
Have you tried using [wrf.extract_times](https://wrf-python.readthedocs.io/en/latest/user_api/generated/wrf.extract_times.html?highlight=extract_times#wrf.extract_times)? I believe the times should be consistent across all data points and locations, so running something like 

` 
# Import packages

from netCDF4 import Dataset
from wrf import (extract_times, ALL_TIMES)
import geocat.datafiles as gdf

###############################################################################
# Read in the data

file_paths = ["wrfout_d01_2005-08-28_00_00_00", "wrfout_d01_2005-08-28_12_00_00"]
wrfin = [Dataset(file_paths[0]), Dataset(file_paths[1])]

time = extract_times(wrfin, ALL_TIMES)

print(time)
`
Should get all times in the datasets.

**Comment by fjime** [comment]
Than you very much Michaela

it was exactly what i needed
