### ISSUE TITLE
proj4 translation issues

### ISSUE THREAD

**Issue by barronh** [NCAR/wrf-python#145]
Thank you for the great package. I was using wrf.PolarStereographic to get the proj4 definition and noticed there were two errors in the proj4 function output. The code below highlights that (1) the lat0 parameter should be lat_0 and is currently being ignored and (2) the unit "meters" should be entered as m. It looks like the `m` issue has been fixed in #127, while the lat0 is currently being silently ignored. The code below demonstrates both issues.

```
import wrf
import pyproj

wp = wrf.PolarStereographic(TRUELAT1=60, TRUELAT2=60, MOAD_CEN_LAT=70, STAND_LON=-156.75, POLE_LAT=90, POLE_LON=-156.75)
proj4string = wp.proj4()
print(proj4string)
# '+proj=stere +units=meters +a=6370000.0 +b=6370000.0 +lat0=90.0 +lon_0=-156.75 +lat_ts=60 +nadgrids=@null'
try:
    testp = pyproj.Proj(proj4string)
except Exception as e:
    print(e)

# Prints error:
# Invalid projection: +proj=stere +units=meters +a=6370000.0 +b=6370000.0 +lat0=90.0 +lon_0=-156.75 +lat_ts=60 +nadgrids=@null +type=crs: (Internal Proj Error: proj_create: Error -7 (unknown unit conversion id))

# meters should be entered as m
fixedunitproj4string = proj4string.replace('meters', 'm')
fixedunitp = pyproj.Proj(fixedunitproj4string )
print(fixedunitp.srs)
# Note that lat0 is ignored
# +proj=stere +units=m +a=6370000.0 +b=6370000.0 +lon_0=-156.75 +lat_ts=60 +nadgrids=@null

# replacing lat0 with lat_0
fixedproj4string = fixedunitproj4string.replace('lat0', 'lat_0')
fixedp = pyproj.Proj(fixedproj4string )
print(fixedp .srs)
# Note that now the lat_0 is correctly passed through.
# +proj=stere +lat_0=90 +lat_ts=60 +lon_0=-156.75 +x_0=0 +y_0=0 +R=6370000 +nadgrids=@null +units=m +no_defs
```

To highlight that this is not a python pyproj issue, the same can be shown from the command line (or in the docs).

```
$ proj -v +proj=stere +units=meters +a=6370000.0 +b=6370000.0 +lat0=90.0 +lon_0=-156.75 +lat_ts=60 +nadgrids=@null
Rel. 4.9.3, 15 August 2016
<proj>:
projection initialization failure
cause: unknown unit conversion id
program abnormally terminated
$ proj -v +proj=stere +units=m +a=6370000.0 +b=6370000.0 +lat0=90.0 +lon_0=-156.75 +lat_ts=60 +nadgrids=@null
#Stereographic
#       Azi, Sph&Ell
#       lat_ts=
# +proj=stere +units=m +a=6370000.0 +b=6370000.0 +lon_0=-156.75 +lat_ts=60
# +nadgrids=@null
#--- following specified but NOT used
# +lat0=90.0
```

These are currently defined on line 827 of projection.py. 

https://github.com/NCAR/wrf-python/blob/e2b6174aa85e5c226cb0bf08a0bdbd3d295a7514/src/wrf/projection.py#L827

**Comment by michaelavs** [comment]
Hi @barronh,
Two quick questions:
1. Is the units issue still persisting even with the fix from issue #127? I believe the associated pull request to fix that issue has been merged, but I know on our side we have had a slight learning curve with how this repository has been run in the past with respect to updates to the source code.
2. With respect to the previous question, how did you download/build WRF-Python on your local? Was it with PyPI, Anaconda, or cloning the GitHub repository? If you did the build through GitHub, I'm curious if doing ```git pull``` on the develop branch would update the software to at least resolve the units issue. 

Both of those questions are more for future reference of making sure users are able to get the most up to date versions of the software. But overall, I agree with the changes you have proposed and will work on implementing them soon to resolve this issue.

**Comment by barronh** [comment]
@michaelavs 

1. My version is pre issue #127, so I assume that part of the issue would be resolved there.
2. PyPI.

I'm a developer and am comfortable pulling the new branch and installing a variety of ways. I left the units as part of the issue because I had already written it up before I found #127. So, I just changed the text to reference it. 

Thanks for doing the work to resolve. I haven't been contributing here, and thought forking/editing/pull requesting for this small pull would be more work than notifying someone already actively developing.

Again, thank you for your work!

**Comment by michaelavs** [comment]
@barronh 
I just created a pull request to address this formatting update, if you would like to look at it, it is linked above this comment (PR #146). If you see anything else that should be updated in that PR let me know and I can address it!

Additionally, we are working to ensure the PyPI and Conda installation methods for WRF-Python are updating regularly when pull requests are merged. Currently, there looks to be an issue with how the repositories are communicating which isn't allowing Conda or PyPI to update to the most recent versions.

**Comment by barronh** [comment]
Thanks. Out of curiosity, is there an issue I can look at to understand the PyPI problem?
