### ISSUE TITLE
wrf-python for python 3.9 on Conda-Forge

### ISSUE THREAD

**Issue by wjcapehart** [NCAR/wrf-python#155]
Hi All.  Is wrf-python on conda forge's 3.9 python feed yet?  Asking for a friend.*

Cheers and Thanks
BIll Capehart
SD Mines

*(I'm the friend.)

**Comment by erogluorhan** [comment]
Hi Bill,

Thanks for asking for your friend :)

Yes, it is there (for linux and osx platforms). Here is the reference
<https://anaconda.org/conda-forge/wrf-python/files> to the files.

Best,

------------------------------------------------------------------------------------------------

Orhan Eroglu

------------------------------------------------------------------------------------------------

**Comment by wjcapehart** [comment]
Cool beans!  Thanks much!

From: Orhan Eroglu ***@***.***>
Reply-To: NCAR/wrf-python ***@***.***>
Date: Wednesday, August 4, 2021 at 10:28 AM
To: NCAR/wrf-python ***@***.***>
Cc: "Capehart, William J" ***@***.***>, Author ***@***.***>
Subject: [EXT] Re: [NCAR/wrf-python] wrf-python for python 3.9 on Conda-Forge (#155)


    *** This email is from an EXTERNAL sender. Use CAUTION before opening attachments or clicking links.***
Hi Bill,

Thanks for asking for your friend :)

Yes, it is there (for linux and osx platforms). Here is the reference
<https://anaconda.org/conda-forge/wrf-python/files> to the files.

Best,

------------------------------------------------------------------------------------------------

Orhan Eroglu

------------------------------------------------------------------------------------------------
