### ISSUE TITLE
MUCAPE Calculation

### ISSUE THREAD

**Issue by zhixiaozhang** [NCAR/wrf-python#156]
When WRF-python calculated the most unstable CAPE, we assumed a parcel with a depth of 500 m is then calculated and centered over this maximum theta-e height level. However, this homogeneity assumption did not work well when the parcel is close to the temperature inversion layer or the parcel is impacted by thin-layer low-level moisture transport. The temperature and moisture vertical-change rate within the parcel can be significant. Therefore, the current MUCAPE tends to reflect more mixed layer than most unstable layer information. That will be great if a new option can be added for calculating MUCAPE by assuming parcel depth is 0. The parcel temperature and moisture are directly obtained at their initial vertical level, instead of using the layer-mean information.

**Comment by michaelavs** [comment]
Hi @zhixiaozhang,
I've been looking into the possibility of adding the ability to calculate most unstable CAPE using what we have in wrf-python already as a base. Were you using cape_2d or cape_3d when doing the calculations you mention?

I am currently comparing functionality in wrf-python to the metpy function "[most_unstable_cape_cin](https://unidata.github.io/MetPy/latest/api/generated/metpy.calc.most_unstable_cape_cin.html?highlight=cape#metpy.calc.most_unstable_cape_cin)", and it would appear that, from my understanding, current functions in wrf-python do not calculate MUCAPE (i.e. MUCAPE is not the same as maximum CAPE, but please correct me if I'm wrong here) and to make the MUCAPE you are describing, there would need to be a new function added to the software overall. With that in mind, any information you can provide such as:
- test data
- expected MUCAPE values for test data
- formulas/functions for calculating the expected values by hand
- functions/code used from wrf-python or other packages to get actual values described in your initial post
would be very helpful so there is a base case on what should be expected when writing and testing the new function.
