### ISSUE TITLE
Problem with interplevel

### ISSUE THREAD

**Issue by iamzdy** [NCAR/wrf-python#159]
Thanks for taking your time to read my issues! I want to interpolate the pressure at specific height but meet a strange problem. Here is the code:
```
level=np.arange(21)
z=getvar(ncfile,'z',units='km')
pres=getvar(ncfile,'pressure')
pres_interp=interplevel(pres,z,level)
```
It turns out that the value at a point at 19km is nan. I try to print the originate pressure and height values of the point at all wrfout levels. All looks good but a height of the point is 19.0. When I change the aimed height to 19.04 like
pres_interp=interplevel(pres,z,19.04)
the result of the point is fine. I think the result of that point is the original value in the previous case but not NAN.
It seems that when the desired level is equal to the initial level, interplevel can not output reasonable value. Is there something wrong when I using interplevel?
![6830d4af24375619903c10459dba96f](https://user-images.githubusercontent.com/65277875/147376753-00e8f696-048e-42c2-bff7-9a611eb00190.png)

**Comment by michaelavs** [comment]
Hi @iamzdy,
Thanks for the great question, it was one that I had myself when using the interplevel function in wrf-python. After doing some more research into this today, I found that the answer is actually based in how an interpolation is calculated mathematically. At its base, an interpolation uses values of data to calculate a number between them, this means that if you were to interpolate to either the absolute max or min level of the dataset, you would get a 0 value in the denominator which leads to NaN being returned. When you adjust your level to 19.04, a very small fraction of a difference, you start to see values that are not NaN because there is no longer a 0 value in the denominator of the function at every point (but some points may still return NaN). Additionally, if you went above the maximum value or below the minimum value, you would also get all NaN values as this would then be an extrapolation calculation. 

If you would like to read a bit more on this, this is the article I was reading that helped to break down the mathematics behind interpolation: https://sciencing.com/what-formulas-do-you-need-to-memorize-for-the-math-ged-exam-12753193.html. Because that article doesn't provide a visual depiction of the formula, here is a link to another article that displays the formula and explains it a bit: https://www.educba.com/interpolation-formula/

I hope this helped clarify what you were asking about, but if not, please let me know!

**Comment by iamzdy** [comment]
@michaelavs 
Thanks for your reply. I read your reply and I guess that the interplevel function used a more complex interpolation algorithm, whose shortage results in the problem. I would like to know whether there is a solution to this question such as adding an 'if-else', but I think it would be time-consuming to trace back after interplevel returning a flawed result.

I am a freshman in python and cannot figure out some effective solutions. All I can think of is the 'if-else' structure to avoid 0 value in the denominator. Sorry to propose that, but it would be better to upgrade the function in your new release! 

Finally, thanks for your contributions to this project. It does provide much convenience to my research. It would be nice to offer me some suggestion on this issue before new release. Thank you!

**Comment by honnorat** [comment]
The code for vertical interpolation is actually a Fortran subroutine called `DINTERP3DZ`: [wrf-python/wrf_user.f90#L67](https://github.com/NCAR/wrf-python/blob/9a812e0d4d32e7f507577fd6e9e3b3d898dbac62/fortran/wrf_user.f90#L67)

And yes indeed, it seems that if your desired interpolation level `desiredloc` is exactly equal to an existing level, the lookup loop never enters the interpolation part and the value remains set to `missingval` (aka. NaN). See line [L#108](https://github.com/NCAR/wrf-python/blob/9a812e0d4d32e7f507577fd6e9e3b3d898dbac62/fortran/wrf_user.f90#L108) (and also [L#167](https://github.com/NCAR/wrf-python/blob/9a812e0d4d32e7f507577fd6e9e3b3d898dbac62/fortran/wrf_user.f90#L167) in `DINTERP3DZ_2DLEV`):

https://github.com/NCAR/wrf-python/blob/9a812e0d4d32e7f507577fd6e9e3b3d898dbac62/fortran/wrf_user.f90#L107-L115

I think the test in L108 should include a non-strict comparison `(zdata(i,j,kp-ip) >= desiredloc)`.

**Comment by michaelavs** [comment]
Hi @iamzdy,
If I am understanding your question correctly, you would like to still plot the lowest level pressure/height data, correct? If so, you could do this with just a basic call to the first index of your wrfin file. The plotting code could look something like:
```
lats, lons = latlon_coords(p[0])

levels = np.arange(np.amin(p[0]), np.amax(p[0], 2.)

plt.contourf(lons,
             lats,
             p[0],
             levels=levels,
             zorder=1,
             transform=crs.PlateCarree())
```
The thing to point out here is that this would not be specific to the lowest pressure level, it would just be the pressures in the lowest **model** level. With that in mind, I did try creating a code that would easily find the lowest/highest pressure level and the coordinating height. However, I found this method wouldn't be the best route as you would most likely have only one low/high value and that wouldn't necessarily give a correct image of the pressures at the specified height. If that wasn't what you are trying to do, I may be able to better assist in a work around if you have an example of what you are aiming to accomplish such as an image of a similar scenario where interpolating to the lowest level was achieved or necessary. Another option is perhaps using the [vertical cross section](https://wrf-python.readthedocs.io/en/latest/user_api/generated/wrf.vertcross.html?highlight=vertcross) function instead which would allow you to visualize all of the data from the very bottom to the very top inclusively. There may be other limitations with a vertical cross section, but I just want to make sure I provide as many resources for you as I can!

**Comment by michaelavs** [comment]
> 

Thanks for the contribution and I will bring this up with the rest of the team next week when we are all back from the holidays!

**Comment by michaelavs** [comment]
> The code for vertical interpolation is actually a Fortran subroutine called `DINTERP3DZ`: [wrf-python/wrf_user.f90#L67](https://github.com/NCAR/wrf-python/blob/9a812e0d4d32e7f507577fd6e9e3b3d898dbac62/fortran/wrf_user.f90#L67)
> 
> And yes indeed, it seems that if your desired interpolation level `desiredloc` is exactly equal to an existing level, the lookup loop never enters the interpolation part and the value remains set to `missingval` (aka. NaN). See line [L#108](https://github.com/NCAR/wrf-python/blob/9a812e0d4d32e7f507577fd6e9e3b3d898dbac62/fortran/wrf_user.f90#L108) (and also [L#167](https://github.com/NCAR/wrf-python/blob/9a812e0d4d32e7f507577fd6e9e3b3d898dbac62/fortran/wrf_user.f90#L167) in `DINTERP3DZ_2DLEV`):
> 
> https://github.com/NCAR/wrf-python/blob/9a812e0d4d32e7f507577fd6e9e3b3d898dbac62/fortran/wrf_user.f90#L107-L115
> 
> I think the test in L108 should include a non-strict comparison `(zdata(i,j,kp-ip) >= desiredloc)`.

Thanks for the contribution and I will bring this up as a possible fix with the rest of the team next week when we are all back from the holidays!

**Comment by iamzdy** [comment]
@michaelavs @honnorat 
Thank you！Have a nice holiday! :)

**Comment by eugene-tam-dpie** [comment]
Apologies for the thread necromancy, but more than a year after the solution below was proposed, this still appears not be implemented (at least not in the master branch)...

> > The code for vertical interpolation is actually a Fortran subroutine called `DINTERP3DZ`: [wrf-python/wrf_user.f90#L67](https://github.com/NCAR/wrf-python/blob/9a812e0d4d32e7f507577fd6e9e3b3d898dbac62/fortran/wrf_user.f90#L67)
> > And yes indeed, it seems that if your desired interpolation level `desiredloc` is exactly equal to an existing level, the lookup loop never enters the interpolation part and the value remains set to `missingval` (aka. NaN). See line [L#108](https://github.com/NCAR/wrf-python/blob/9a812e0d4d32e7f507577fd6e9e3b3d898dbac62/fortran/wrf_user.f90#L108) (and also [L#167](https://github.com/NCAR/wrf-python/blob/9a812e0d4d32e7f507577fd6e9e3b3d898dbac62/fortran/wrf_user.f90#L167) in `DINTERP3DZ_2DLEV`):
> > https://github.com/NCAR/wrf-python/blob/9a812e0d4d32e7f507577fd6e9e3b3d898dbac62/fortran/wrf_user.f90#L107-L115
> > 
> > I think the test in L108 should include a non-strict comparison `(zdata(i,j,kp-ip) >= desiredloc)`.
> 
> Thanks for the contribution and I will bring this up as a possible fix with the rest of the team next week when we are all back from the holidays!
