### ISSUE TITLE
Configuration routines for third party packages (`enable_*()`, `disable_*()`, `*_enabled()`) do not work 

### ISSUE THREAD

**Issue by sfalmo** [NCAR/wrf-python#168]
By default, `wrf-python` checks if a useful third party package such as `xarray`, `cartopy`, `basemap` or `PyNGL` is installed and uses it in this case. Additionally, there are some configuration routines (https://wrf-python.readthedocs.io/en/latest/user_api/index.html#configuration-routines) for enabling or disabling those third party packages regardless of the default behavior.

These configuration routines do not work. For example,

```python
import wrf

wrf.disable_xarray()
print(wrf.xarray_enabled())
```

prints `True` if `xarray` is installed and subsequent calls to `wrf.getvar` still return `xarray`s.

**Comment by michaelavs** [comment]
Hi @sfalmo,
Thank you for opening this issue and a corresponding PR! I will be reviewing the PR in the next week to make sure everything runs smoothly before approval. Once approved, we can merge and release the fix for wrf-python.
