### ISSUE TITLE
Document wind direction

### ISSUE THREAD

**Issue by andreas-h** [NCAR/wrf-python#18]
In the *Table of Available Diagnostics*, please indicate if all the `wdir` diagnostics mean the `wind_to_direction` or the `wind_from_direction` (speaking in [CF standard name](http://cfconventions.org/Data/cf-standard-names/43/build/cf-standard-name-table.html) language).

**Comment by bladwig1** [comment]
It's meteorological wind direction, which is almost always "wind_from_direction".  Didn't realize netcdf-cf supported a wind_to_direction.  I'll make a note in the next documentation update.

**Comment by andreas-h** [comment]
Thanks, Bill!
