### ISSUE TITLE
Bug when reading wind from MFDataset

### ISSUE THREAD

**Issue by andreas-h** [NCAR/wrf-python#19]
After loading an `MFDataset` with `xarray`,

    ds = xr.open_mfdataset(filename)

I would like to load wind information.  So I first create a list of the netCDF Dataset objects,

    objs = [file_obj_.ds for file_obj_ in ds._file_obj.file_objs]

and then try to load using `getvar`:

    wrf.getvar(objs, varname, timeidx=0)

This works just fine.

However, when I specify `timeidx=None` to read all time slices at once, I get a 

    /home/eb/software/wrf-python/1.0b3-intel-2016a-Python-3.5.1/lib/python3.5/site-packages/wrf_python-1.0b3-py3.5-linux-x86_64.egg/wrf/wind.py in _calc_wspd_wdir(u, v, two_d, units)
         97             (0, Ellipsis, slice(None), slice(None)))
         98 
    ---> 99     result[idxs0] = wspd[:]
        100     result[idxs1] = wdir[:]
        101 
    
    ValueError: could not broadcast input array from shape (361,210,210) into shape (2,210,210)

I'm using version 1.0b3 of wrf-python.

**Comment by bladwig1** [comment]
I am guessing your varname was either wspd_wdir10 or uvmet10_wspd_wdir.  I was able to reproduce this as well.   I'll try to get out a hotfix soon.

**Comment by bladwig1** [comment]
If you want to quickly patch your code before the hotfix is out, modify _calc_wspd_wdir in site-packages/wrf_python-1.0b3-py3.5-linux-x86_64.egg/wrf/wind.py to be this:

``` python

def _calc_wspd_wdir(u, v, two_d, units):
    """Return the wind speed and wind direction.
    
    The leftmost dimension of the returned array represents two different 
    quantities:
        
        - return_val[0,...] will contain WSPD
        - return_val[1,...] will contain WDIR
    
    Args:
    
        u (:class:`numpy.ndarray`): The u component of the wind.
        
        v (:class:`numpy.ndarray`): The v component of the wind.
        
        two_d (:obj:`bool`): Set to True if the u,v wind components are 
            for a two-dimensional array (no height dimension).  Otherwise,
            set to False.
            
        units (:obj:`str`): The desired units.  Refer to the :meth:`getvar` 
            product table for a list of available units for 'uvmet_wspd_wdir'.  
            Default is 'm s-1'.
            
    Returns:
    
        :class:`numpy.ndarray`: The wind speed and wind direction, whose 
        leftmost dimension is 2 (0=WSPD, 1=WDIR).
    
    """
    wspd = _calc_wspd(u, v, units)
    wdir = _calc_wdir(u, v)

    idx_end = -2 if two_d else -3
    
    outdims = [2] + list(wspd.shape[0:idx_end]) + list(wspd.shape[idx_end:])
    
    result = np.zeros(outdims, wspd.dtype)
    
    idxs0 = ((0,Ellipsis, slice(None), slice(None), slice(None)) 
            if not two_d else 
            (0, Ellipsis, slice(None), slice(None)))
    
    idxs1 = ((1, Ellipsis, slice(None), slice(None), slice(None)) 
            if not two_d else 
            (1, Ellipsis, slice(None), slice(None)))
    
    result[idxs0] = wspd[:]
    result[idxs1] = wdir[:]
    
    return result
```

**Comment by andreas-h** [comment]
Yes, my `varname` is `uvmet10_wspd_wdir`.  Thanks for the super-fast help! I'll try out your fix later and will let you know if my problem is solved.
