### ISSUE TITLE
uvmet10_wspd_wdir mixes up wind speed and direction

### ISSUE THREAD

**Issue by Peter9192** [NCAR/wrf-python#21]
Using `wrf.getvar(wrfin,'uvmet10_wspd_wdir)`, the returned DataArray has a dimension `wpsd_wdir` with values `wspd` and `wdir`. However, it seems that the `wspd` array contains the wind direction and vice versa.

**Comment by bladwig1** [comment]
See #19 .

A hotfix should be out for this in the next few days.
