### ISSUE TITLE
getvar with uvmet10_wspd_wdir and ALL_TIMES gives broadcasting problem

### ISSUE THREAD

**Issue by Peter9192** [NCAR/wrf-python#22]
`wrf.getvar(wrfin,uvmet10_wspd_wdir,timeidx=wrf.ALL_TIMES)'  gives:
ValueError: could not broadcast input array from shape (35,599,599) into shape (2,599,599).

It should produce a 4d output: wspd/wdir, time, lat, lon (2,35,599,599).
`uvmet10` works fine by the way, so the problem must be in the conversion to wspd/wdir.

**Comment by bladwig1** [comment]
See #19 .

A hotfix should be out for this in the next few days.
