### ISSUE TITLE
error when install wrf-python

### ISSUE THREAD

**Issue by Kevinello** [NCAR/wrf-python#237]
Error when i use pip to install wrf-python:
```shell
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting wrf-python
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/19/b9/ac6886e7995a9c83f393f758fd4803ab13bda0e57f8d3540f6d3a9f070db/wrf-python-1.3.4.1.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /root/.cache/pypoetry/virtualenvs/python-plot-u4OVFNWo-py3.8/bin/python: No module named pip
      Traceback (most recent call last):
        File "/root/.cache/pypoetry/virtualenvs/python-plot-u4OVFNWo-py3.8/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/.cache/pypoetry/virtualenvs/python-plot-u4OVFNWo-py3.8/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/.cache/pypoetry/virtualenvs/python-plot-u4OVFNWo-py3.8/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-_nr8l14r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-_nr8l14r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-_nr8l14r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-_nr8l14r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I try to install it through source code referencing to [documentation](https://wrf-python.readthedocs.io/en/latest/installation.html#installing-via-source-code), but it still raised the same error

And i'm 100% percent sure that i have numpy in my virtualenv(created by poetry), and i run `pip install wrf-python` while the virtualenv is activated(in the `poetry shell`) 
<img width="807" alt="image" src="https://github.com/NCAR/wrf-python/assets/56342249/76f29a2e-6420-4949-8c7d-04ed50ac0df1">

**Comment by omdaniel** [comment]
I haven't examined the source code but from my own testing I surmise a couple of things going on here.

First, wrf-python does not play nice with build isolation. If you look up the stack trace you will see "No module named pip"

In my case I am using uv and I disable build isolation with --no-build-isolation and then the legacy installer will complain that I need pip installed, and then it will complain that I need wheel installed, and lastly on Windows without compilers will fail when it attempts to compile (if you have "Microsoft C++ Build Tools" on Windows it should succeed here, or if you are on Windows)

Second, wrf-python still relies on distutils, deprecated after numpy 1.23 and fully removed in 1.26. So to even get as far as the above suggestion will get, you need to install numpy<1.26

**Comment by DWesl** [comment]
> I haven't examined the source code but from my own testing I surmise a couple of things going on here.
> 
> First, wrf-python does not play nice with build isolation. If you look up the stack trace you will see "No module named pip"

https://github.com/NCAR/wrf-python/blob/cec1f70ceff9e4e051e4e0ed73104c60220ab0eb/setup.py#L14
> 
> In my case I am using uv and I disable build isolation with --no-build-isolation and then the legacy installer will complain that I need pip installed, and then it will complain that I need wheel installed, and lastly on Windows without compilers will fail when it attempts to compile (if you have "Microsoft C++ Build Tools" on Windows it should succeed here, or if you are on Linux it should succeed here). However, requiring pip and wheel in your virtual environment is inconvenient and will cause issues with many modern tools that assume the packages can be installed with build isolation.

I thought pip only enabled build isolation if it found `pyproject.toml`, has that changed recently?  

The failure without compilers is expected, wrf-python not putting numpy into setuptools's old `build_requires` is less so.
> 
> Second, wrf-python still relies on distutils, deprecated after numpy 1.23 and fully removed in 1.26. So to even get as far as the above suggestion will get, you need to install numpy<1.26

Specifically on [NumPy distutils, which looks like it's around for another year on python 3.11 and will never be on 3.12](https://numpy.org/doc/stable/reference/distutils_status_migration.html), so there's an argument for `python_requires="<3.12"` in the setup script.

That link proposes suggestions for migrating the build for python 3.12, specifically [meson](https://mesonbuild.com/) through [meson-python](https://meson-python.readthedocs.io/) or [CMake](https://cmake.org/) using [scikit-build-core](https://scikit-build-core.readthedocs.io/en/latest/), if anyone wants to try for a PR.

**Comment by arbraham** [comment]
I am facing the same issue and exhaused all method. When can this issue be resolved?

**Comment by nibheis** [comment]
Hi there !

I'm also trying to have `wrf-python` pip-installed with Python 3.12...
`nympy<1.26` (as recommended in this issuel) can not be installed. Python 3.12 requires `numpy>=1.26.4`

I have been testing PR241 (migrating wrf-python to pyproject.toml) unsuccessfully. Here is the pip install from sources output:

```
Processing /root/wrf-python-test/wrf-python
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/opt/jlab-env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/jlab-env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/jlab-env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-cf88yuo9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-cf88yuo9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-cf88yuo9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
      ModuleNotFoundError: No module named 'numpy.distutils'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I see many files in wrf-python still referencing `numpy.distutils.*`... which is obviously not present anymore in numpy 1.26.4

Any suggestion? Anyone got `wrf-python` installed with python 3.12?

**Comment by DWesl** [comment]
Have you tried installing #242, which was designed to move away from `numpy.distutils`, rather than with #241, which was designed to ensure `numpy` was installed when `pip` built `wrf-python`, as suggested [above](https://github.com/NCAR/wrf-python/issues/237#issuecomment-2127217317)?

**Comment by nibheis** [comment]
Thanks @DWesl, I confirm #242 works for me, `wrf-python==1.3.4.1` is now installed. 

However is pulls in `basemap==1.4.1` which pulls in older versions of `matplotlib` and `packaging` in my env... but this is another issue.
