### ISSUE TITLE
Error heppend during the conda install

### ISSUE THREAD

**Issue by OMGTaylor0814** [NCAR/wrf-python#239]
`PS Q:\wrf> conda install -c conda-forge wrf-python
Collecting package metadata (current_repodata.json): done
Solving environment: | 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/noarch::alabaster==0.7.12=pyhd3eb1b0_0
  - defaults/win-64::anaconda==2022.10=py39_0
  - defaults/win-64::anaconda-client==1.11.0=py39haa95532_0
  - defaults/win-64::anaconda-navigator==2.4.0=py39haa95532_0
  - defaults/win-64::anaconda-project==0.11.1=py39haa95532_0
  - defaults/win-64::anyio==3.5.0=py39haa95532_0
  - defaults/noarch::appdirs==1.4.4=pyhd3eb1b0_0
  - defaults/noarch::argon2-cffi==21.3.0=pyhd3eb1b0_0
  - defaults/win-64::argon2-cffi-bindings==21.2.0=py39h2bbff1b_0
  - defaults/noarch::arrow==1.2.2=pyhd3eb1b0_0
  - defaults/win-64::astroid==2.11.7=py39haa95532_0
  - defaults/win-64::astropy==5.1=py39h080aedc_0
  - defaults/noarch::atomicwrites==1.4.0=py_0
  - defaults/noarch::attrs==21.4.0=pyhd3eb1b0_0
  - defaults/noarch::automat==20.2.0=py_0
  - defaults/noarch::autopep8==1.6.0=pyhd3eb1b0_1
  - defaults/noarch::babel==2.9.1=pyhd3eb1b0_0
  - defaults/noarch::backcall==0.2.0=pyhd3eb1b0_0
  - defaults/noarch::backports==1.1=pyhd3eb1b0_0
  - defaults/noarch::backports.functools_lru_cache==1.6.4=pyhd3eb1b0_0
  - defaults/noarch::backports.tempfile==1.0=pyhd3eb1b0_1
  - defaults/noarch::backports.weakref==1.0.post1=py_1
  - defaults/win-64::bcrypt==3.2.0=py39h2bbff1b_1
  - defaults/win-64::beautifulsoup4==4.11.1=py39haa95532_0
  - defaults/noarch::binaryornot==0.4.4=pyhd3eb1b0_1
  - defaults/win-64::bitarray==2.5.1=py39h2bbff1b_0
  - defaults/win-64::bkcharts==0.2=py39haa95532_1
  - defaults/win-64::black==22.6.0=py39haa95532_0
  - defaults/noarch::bleach==4.1.0=pyhd3eb1b0_0
  - defaults/win-64::bokeh==2.4.3=py39haa95532_0
  - defaults/win-64::boto3==1.24.28=py39haa95532_0
  - defaults/win-64::botocore==1.27.28=py39haa95532_0
  - defaults/win-64::bottleneck==1.3.5=py39h080aedc_0
  - defaults/win-64::brotlipy==0.7.0=py39h2bbff1b_1003
  - defaults/win-64::certifi==2022.9.14=py39haa95532_0
  - defaults/win-64::cffi==1.15.1=py39h2bbff1b_0
  - defaults/win-64::chardet==4.0.0=py39haa95532_1003
  - defaults/noarch::charset-normalizer==2.0.4=pyhd3eb1b0_0
  - defaults/win-64::click==8.0.4=py39haa95532_0
  - defaults/noarch::cloudpickle==2.0.0=pyhd3eb1b0_0
  - defaults/win-64::clyent==1.2.2=py39haa95532_1
  - defaults/win-64::colorama==0.4.5=py39haa95532_0
  - defaults/win-64::colorcet==3.0.0=py39haa95532_0
  - defaults/win-64::comtypes==1.1.10=py39haa95532_1002
  - defaults/win-64::conda==22.9.0=py39haa95532_0
  - defaults/win-64::conda-build==3.22.0=py39haa95532_0
  - defaults/win-64::conda-content-trust==0.1.3=py39haa95532_0
  - defaults/noarch::conda-pack==0.6.0=pyhd3eb1b0_0
  - defaults/win-64::conda-package-handling==1.9.0=py39h8cc25b3_0
  - defaults/win-64::conda-repo-cli==1.0.20=py39haa95532_0
  - defaults/noarch::conda-token==0.4.0=pyhd3eb1b0_0
  - defaults/noarch::conda-verify==3.4.2=py_1
  - defaults/win-64::console_shortcut==0.1.1=4
  - defaults/noarch::constantly==15.1.0=pyh2b92418_0
  - defaults/noarch::cookiecutter==1.7.3=pyhd3eb1b0_0
  - defaults/win-64::cryptography==37.0.1=py39h21b164f_0
  - defaults/noarch::cssselect==1.1.0=pyhd3eb1b0_0
  - defaults/noarch::cycler==0.11.0=pyhd3eb1b0_0
  - defaults/win-64::cython==0.29.32=py39hd77b12b_0
  - defaults/win-64::cytoolz==0.11.0=py39h2bbff1b_0
  - defaults/win-64::daal4py==2021.6.0=py39h757b272_1
  - defaults/win-64::dask==2022.7.0=py39haa95532_0
  - defaults/win-64::dask-core==2022.7.0=py39haa95532_0
  - defaults/noarch::dataclasses==0.8=pyh6d0b6a4_7
  - defaults/win-64::datashader==0.14.1=py39haa95532_0
  - defaults/win-64::datashape==0.5.4=py39haa95532_1
  - defaults/win-64::debugpy==1.5.1=py39hd77b12b_0
  - defaults/noarch::decorator==5.1.1=pyhd3eb1b0_0
  - defaults/noarch::defusedxml==0.7.1=pyhd3eb1b0_0
  - defaults/noarch::diff-match-patch==20200713=pyhd3eb1b0_0
  - defaults/noarch::dill==0.3.4=pyhd3eb1b0_0
  - defaults/win-64::distributed==2022.7.0=py39haa95532_0
  - defaults/win-64::docutils==0.18.1=py39haa95532_3
  - defaults/win-64::entrypoints==0.4=py39haa95532_0
  - defaults/win-64::et_xmlfile==1.1.0=py39haa95532_0
  - defaults/noarch::filelock==3.6.0=pyhd3eb1b0_0
  - defaults/noarch::flake8==4.0.1=pyhd3eb1b0_1
  - defaults/noarch::flask==1.1.2=pyhd3eb1b0_0
  - defaults/noarch::fonttools==4.25.0=pyhd3eb1b0_0
  - defaults/win-64::fsspec==2022.7.1=py39haa95532_0
  - defaults/win-64::future==0.18.2=py39haa95532_1
  - defaults/win-64::gensim==4.1.2=py39hd77b12b_0
  - defaults/noarch::glob2==0.7=pyhd3eb1b0_0
  - defaults/win-64::greenlet==1.1.1=py39hd77b12b_0
  - defaults/win-64::h5py==3.7.0=py39h3de5c98_0
  - defaults/noarch::heapdict==1.0.1=pyhd3eb1b0_0
  - defaults/win-64::holoviews==1.15.0=py39haa95532_0
  - defaults/win-64::hvplot==0.8.0=py39haa95532_0
  - defaults/noarch::hyperlink==21.0.0=pyhd3eb1b0_0
  - defaults/noarch::idna==3.3=pyhd3eb1b0_0
  - defaults/win-64::imagecodecs==2021.8.26=py39hc0a7faf_1
  - defaults/win-64::imageio==2.19.3=py39haa95532_0
  - defaults/win-64::imagesize==1.4.1=py39haa95532_0
  - defaults/win-64::importlib-metadata==4.11.3=py39haa95532_0
  - defaults/noarch::importlib_metadata==4.11.3=hd3eb1b0_0
  - defaults/noarch::incremental==21.3.0=pyhd3eb1b0_0
  - defaults/win-64::inflection==0.5.1=py39haa95532_0
  - defaults/noarch::iniconfig==1.1.1=pyhd3eb1b0_0
  - defaults/noarch::intake==0.6.5=pyhd3eb1b0_0
  - defaults/noarch::intervaltree==3.1.0=pyhd3eb1b0_0
  - defaults/win-64::ipykernel==6.15.2=py39haa95532_0
  - defaults/win-64::ipython==7.31.1=py39haa95532_1
  - defaults/noarch::ipython_genutils==0.2.0=pyhd3eb1b0_1
  - defaults/noarch::ipywidgets==7.6.5=pyhd3eb1b0_1
  - defaults/noarch::isort==5.9.3=pyhd3eb1b0_0
  - defaults/noarch::itemadapter==0.3.0=pyhd3eb1b0_0
  - defaults/noarch::itemloaders==1.0.4=pyhd3eb1b0_1
  - defaults/noarch::itsdangerous==2.0.1=pyhd3eb1b0_0
  - defaults/noarch::jdcal==1.4.1=pyhd3eb1b0_0
  - defaults/win-64::jedi==0.18.1=py39haa95532_1
  - defaults/win-64::jellyfish==0.9.0=py39h2bbff1b_0
  - defaults/noarch::jinja2==2.11.3=pyhd3eb1b0_0
  - defaults/noarch::jinja2-time==0.2.0=pyhd3eb1b0_3
  - defaults/noarch::jmespath==0.10.0=pyhd3eb1b0_0
  - defaults/noarch::joblib==1.1.0=pyhd3eb1b0_0
  - defaults/noarch::json5==0.9.6=pyhd3eb1b0_0
  - defaults/win-64::jsonschema==4.16.0=py39haa95532_0
  - defaults/win-64::jupyter==1.0.0=py39haa95532_8
  - defaults/win-64::jupyterlab==3.4.4=py39haa95532_0
  - defaults/noarch::jupyterlab_pygments==0.1.2=py_0
  - defaults/noarch::jupyterlab_server==2.10.3=pyhd3eb1b0_1
  - defaults/noarch::jupyterlab_widgets==1.0.0=pyhd3eb1b0_1
  - defaults/win-64::jupyter_client==7.3.4=py39haa95532_0
  - defaults/noarch::jupyter_console==6.4.3=pyhd3eb1b0_0
  - defaults/win-64::jupyter_core==4.11.1=py39haa95532_0
  - defaults/win-64::jupyter_server==1.18.1=py39haa95532_0
  - defaults/win-64::keyring==23.4.0=py39haa95532_0
  - defaults/win-64::kiwisolver==1.4.2=py39hd77b12b_0
  - defaults/win-64::lazy-object-proxy==1.6.0=py39h2bbff1b_0
  - defaults/win-64::llvmlite==0.38.0=py39h23ce68f_0
  - defaults/win-64::locket==1.0.0=py39haa95532_0
  - defaults/win-64::lxml==4.9.1=py39h1985fb9_0
  - defaults/win-64::lz4==3.1.3=py39h2bbff1b_0
  - defaults/win-64::markdown==3.3.4=py39haa95532_0
  - defaults/win-64::markupsafe==2.0.1=py39h2bbff1b_0
  - defaults/win-64::matplotlib==3.5.2=py39haa95532_0
  - defaults/win-64::matplotlib-base==3.5.2=py39hd77b12b_0
  - defaults/win-64::matplotlib-inline==0.1.6=py39haa95532_0
  - defaults/win-64::mccabe==0.6.1=py39haa95532_2
  - defaults/win-64::menuinst==1.4.19=py39h59b6b97_0
  - defaults/win-64::mistune==0.8.4=py39h2bbff1b_1000
  - defaults/win-64::mkl-service==2.4.0=py39h2bbff1b_0
  - defaults/win-64::mkl_fft==1.3.1=py39h277e83a_0
  - defaults/win-64::mkl_random==1.2.2=py39hf11a4ad_0
  - defaults/noarch::mock==4.0.3=pyhd3eb1b0_0
  - defaults/win-64::mpmath==1.2.1=py39haa95532_0
  - defaults/win-64::msgpack-python==1.0.3=py39h59b6b97_0
  - defaults/win-64::multipledispatch==0.6.0=py39haa95532_0
  - defaults/noarch::munkres==1.1.4=py_0
  - defaults/win-64::mypy_extensions==0.4.3=py39haa95532_1
  - defaults/win-64::navigator-updater==0.3.0=py39haa95532_0
  - defaults/noarch::nbclassic==0.3.5=pyhd3eb1b0_0
  - defaults/win-64::nbclient==0.5.13=py39haa95532_0
  - defaults/win-64::nbconvert==6.4.4=py39haa95532_0
  - defaults/win-64::nbformat==5.5.0=py39haa95532_0
  - defaults/win-64::nest-asyncio==1.5.5=py39haa95532_0
  - defaults/win-64::networkx==2.8.4=py39haa95532_0
  - defaults/noarch::nltk==3.7=pyhd3eb1b0_0
  - defaults/noarch::nose==1.3.7=pyhd3eb1b0_1008
  - defaults/win-64::notebook==6.4.12=py39haa95532_0
  - defaults/win-64::numba==0.55.1=py39hf11a4ad_0
  - defaults/win-64::numexpr==2.8.3=py39hb80d3ca_0
  - defaults/win-64::numpy==1.21.5=py39h7a0a035_3
  - defaults/win-64::numpy-base==1.21.5=py39hca35cd5_3
  - defaults/win-64::numpydoc==1.4.0=py39haa
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/noarch::alabaster==0.7.12=pyhd3eb1b0_0
  - defaults/win-64::anaconda==2022.10=py39_0
  - defaults/win-64::anaconda-client==1.11.0=py39haa95532_0
  - defaults/win-64::anaconda-navigator==2.4.0=py39haa95532_0
  - defaults/win-64::anaconda-project==0.11.1=py39haa95532_0
  - defaults/win-64::anyio==3.5.0=py39haa95532_0
  - defaults/noarch::appdirs==1.4.4=pyhd3eb1b0_0
  - defaults/noarch::argon2-cffi==21.3.0=pyhd3eb1b0_0
  - defaults/win-64::argon2-cffi-bindings==21.2.0=py39h2bbff1b_0
  - defaults/noarch::arrow==1.2.2=pyhd3eb1b0_0
  - defaults/win-64::astroid==2.11.7=py39haa95532_0
  - defaults/win-64::astropy==5.1=py39h080aedc_0
  - defaults/noarch::atomicwrites==1.4.0=py_0
  - defaults/noarch::attrs==21.4.0=pyhd3eb1b0_0
  - defaults/noarch::automat==20.2.0=py_0
  - defaults/noarch::autopep8==1.6.0=pyhd3eb1b0_1
  - defaults/noarch::babel==2.9.1=pyhd3eb1b0_0
  - defaults/noarch::backcall==0.2.0=pyhd3eb1b0_0
  - defaults/noarch::backports==1.1=pyhd3eb1b0_0
  - defaults/noarch::backports.functools_lru_cache==1.6.4=pyhd3eb1b0_0
  - defaults/noarch::backports.tempfile==1.0=pyhd3eb1b0_1
  - defaults/noarch::backports.weakref==1.0.post1=py_1
  - defaults/win-64::bcrypt==3.2.0=py39h2bbff1b_1
  - defaults/win-64::beautifulsoup4==4.11.1=py39haa95532_0
  - defaults/noarch::binaryornot==0.4.4=pyhd3eb1b0_1
  - defaults/win-64::bitarray==2.5.1=py39h2bbff1b_0
  - defaults/win-64::bkcharts==0.2=py39haa95532_1
  - defaults/win-64::black==22.6.0=py39haa95532_0
  - defaults/noarch::bleach==4.1.0=pyhd3eb1b0_0
  - defaults/win-64::bokeh==2.4.3=py39haa95532_0
  - defaults/win-64::boto3==1.24.28=py39haa95532_0
  - defaults/win-64::botocore==1.27.28=py39haa95532_0
  - defaults/win-64::bottleneck==1.3.5=py39h080aedc_0
  - defaults/win-64::brotlipy==0.7.0=py39h2bbff1b_1003
  - defaults/win-64::certifi==2022.9.14=py39haa95532_0
  - defaults/win-64::cffi==1.15.1=py39h2bbff1b_0
  - defaults/win-64::chardet==4.0.0=py39haa95532_1003
  - defaults/noarch::charset-normalizer==2.0.4=pyhd3eb1b0_0
  - defaults/win-64::click==8.0.4=py39haa95532_0
  - defaults/noarch::cloudpickle==2.0.0=pyhd3eb1b0_0
  - defaults/win-64::clyent==1.2.2=py39haa95532_1
  - defaults/win-64::colorama==0.4.5=py39haa95532_0
  - defaults/win-64::colorcet==3.0.0=py39haa95532_0
  - defaults/win-64::comtypes==1.1.10=py39haa95532_1002
  - defaults/win-64::conda==22.9.0=py39haa95532_0
  - defaults/win-64::conda-build==3.22.0=py39haa95532_0
  - defaults/win-64::conda-content-trust==0.1.3=py39haa95532_0
  - defaults/noarch::conda-pack==0.6.0=pyhd3eb1b0_0
  - defaults/win-64::conda-package-handling==1.9.0=py39h8cc25b3_0
  - defaults/win-64::conda-repo-cli==1.0.20=py39haa95532_0
  - defaults/noarch::conda-token==0.4.0=pyhd3eb1b0_0
  - defaults/noarch::conda-verify==3.4.2=py_1
  - defaults/win-64::console_shortcut==0.1.1=4
  - defaults/noarch::constantly==15.1.0=pyh2b92418_0
  - defaults/noarch::cookiecutter==1.7.3=pyhd3eb1b0_0
  - defaults/win-64::cryptography==37.0.1=py39h21b164f_0
  - defaults/noarch::cssselect==1.1.0=pyhd3eb1b0_0
  - defaults/noarch::cycler==0.11.0=pyhd3eb1b0_0
  - defaults/win-64::cython==0.29.32=py39hd77b12b_0
  - defaults/win-64::cytoolz==0.11.0=py39h2bbff1b_0
  - defaults/win-64::daal4py==2021.6.0=py39h757b272_1
  - defaults/win-64::dask==2022.7.0=py39haa95532_0
  - defaults/win-64::dask-core==2022.7.0=py39haa95532_0
  - defaults/noarch::dataclasses==0.8=pyh6d0b6a4_7
  - defaults/win-64::datashader==0.14.1=py39haa95532_0
  - defaults/win-64::datashape==0.5.4=py39haa95532_1
  - defaults/win-64::debugpy==1.5.1=py39hd77b12b_0
  - defaults/noarch::decorator==5.1.1=pyhd3eb1b0_0
  - defaults/noarch::defusedxml==0.7.1=pyhd3eb1b0_0
  - defaults/noarch::diff-match-patch==20200713=pyhd3eb1b0_0
  - defaults/noarch::dill==0.3.4=pyhd3eb1b0_0
  - defaults/win-64::distributed==2022.7.0=py39haa95532_0
  - defaults/win-64::docutils==0.18.1=py39haa95532_3
  - defaults/win-64::entrypoints==0.4=py39haa95532_0
  - defaults/win-64::et_xmlfile==1.1.0=py39haa95532_0
  - defaults/noarch::filelock==3.6.0=pyhd3eb1b0_0
  - defaults/noarch::flake8==4.0.1=pyhd3eb1b0_1
  - defaults/noarch::flask==1.1.2=pyhd3eb1b0_0
  - defaults/noarch::fonttools==4.25.0=pyhd3eb1b0_0
  - defaults/win-64::fsspec==2022.7.1=py39haa95532_0
  - defaults/win-64::future==0.18.2=py39haa95532_1
  - defaults/win-64::gensim==4.1.2=py39hd77b12b_0
  - defaults/noarch::glob2==0.7=pyhd3eb1b0_0
  - defaults/win-64::greenlet==1.1.1=py39hd77b12b_0
  - defaults/win-64::h5py==3.7.0=py39h3de5c98_0
  - defaults/noarch::heapdict==1.0.1=pyhd3eb1b0_0
  - defaults/win-64::holoviews==1.15.0=py39haa95532_0
  - defaults/win-64::hvplot==0.8.0=py39haa95532_0
  - defaults/noarch::hyperlink==21.0.0=pyhd3eb1b0_0
  - defaults/noarch::idna==3.3=pyhd3eb1b0_0
  - defaults/win-64::imagecodecs==2021.8.26=py39hc0a7faf_1
  - defaults/win-64::imageio==2.19.3=py39haa95532_0
  - defaults/win-64::imagesize==1.4.1=py39haa95532_0
  - defaults/win-64::importlib-metadata==4.11.3=py39haa95532_0
  - defaults/noarch::importlib_metadata==4.11.3=hd3eb1b0_0
  - defaults/noarch::incremental==21.3.0=pyhd3eb1b0_0
  - defaults/win-64::inflection==0.5.1=py39haa95532_0
  - defaults/noarch::iniconfig==1.1.1=pyhd3eb1b0_0
  - defaults/noarch::intake==0.6.5=pyhd3eb1b0_0
  - defaults/noarch::intervaltree==3.1.0=pyhd3eb1b0_0
  - defaults/win-64::ipykernel==6.15.2=py39haa95532_0
  - defaults/win-64::ipython==7.31.1=py39haa95532_1
  - defaults/noarch::ipython_genutils==0.2.0=pyhd3eb1b0_1
  - defaults/noarch::ipywidgets==7.6.5=pyhd3eb1b0_1
  - defaults/noarch::isort==5.9.3=pyhd3eb1b0_0
  - defaults/noarch::itemadapter==0.3.0=pyhd3eb1b0_0
  - defaults/noarch::itemloaders==1.0.4=pyhd3eb1b0_1
  - defaults/noarch::itsdangerous==2.0.1=pyhd3eb1b0_0
  - defaults/noarch::jdcal==1.4.1=pyhd3eb1b0_0
  - defaults/win-64::jedi==0.18.1=py39haa95532_1
  - defaults/win-64::jellyfish==0.9.0=py39h2bbff1b_0
  - defaults/noarch::jinja2==2.11.3=pyhd3eb1b0_0
  - defaults/noarch::jinja2-time==0.2.0=pyhd3eb1b0_3
  - defaults/noarch::jmespath==0.10.0=pyhd3eb1b0_0
  - defaults/noarch::joblib==1.1.0=pyhd3eb1b0_0
  - defaults/noarch::json5==0.9.6=pyhd3eb1b0_0
  - defaults/win-64::jsonschema==4.16.0=py39haa95532_0
  - defaults/win-64::jupyter==1.0.0=py39haa95532_8
  - defaults/win-64::jupyterlab==3.4.4=py39haa95532_0
  - defaults/noarch::jupyterlab_pygments==0.1.2=py_0
  - defaults/noarch::jupyterlab_server==2.10.3=pyhd3eb1b0_1
  - defaults/noarch::jupyterlab_widgets==1.0.0=pyhd3eb1b0_1
  - defaults/win-64::jupyter_client==7.3.4=py39haa95532_0
  - defaults/noarch::jupyter_console==6.4.3=pyhd3eb1b0_0
  - defaults/win-64::jupyter_core==4.11.1=py39haa95532_0
  - defaults/win-64::jupyter_server==1.18.1=py39haa95532_0
  - defaults/win-64::keyring==23.4.0=py39haa95532_0
  - defaults/win-64::kiwisolver==1.4.2=py39hd77b12b_0
  - defaults/win-64::lazy-object-proxy==1.6.0=py39h2bbff1b_0
  - defaults/win-64::llvmlite==0.38.0=py39h23ce68f_0
  - defaults/win-64::locket==1.0.0=py39haa95532_0
  - defaults/win-64::lxml==4.9.1=py39h1985fb9_0
  - defaults/win-64::lz4==3.1.3=py39h2bbff1b_0
  - defaults/win-64::markdown==3.3.4=py39haa95532_0
  - defaults/win-64::markupsafe==2.0.1=py39h2bbff1b_0
  - defaults/win-64::matplotlib==3.5.2=py39haa95532_0
  - defaults/win-64::matplotlib-base==3.5.2=py39hd77b12b_0
  - defaults/win-64::matplotlib-inline==0.1.6=py39haa95532_0
  - defaults/win-64::mccabe==0.6.1=py39haa95532_2
  - defaults/win-64::menuinst==1.4.19=py39h59b6b97_0
  - defaults/win-64::mistune==0.8.4=py39h2bbff1b_1000
  - defaults/win-64::mkl-service==2.4.0=py39h2bbff1b_0
  - defaults/win-64::mkl_fft==1.3.1=py39h277e83a_0
  - defaults/win-64::mkl_random==1.2.2=py39hf11a4ad_0
  - defaults/noarch::mock==4.0.3=pyhd3eb1b0_0
  - defaults/win-64::mpmath==1.2.1=py39haa95532_0
  - defaults/win-64::msgpack-python==1.0.3=py39h59b6b97_0
  - defaults/win-64::multipledispatch==0.6.0=py39haa95532_0
  - defaults/noarch::munkres==1.1.4=py_0
  - defaults/win-64::mypy_extensions==0.4.3=py39haa95532_1
  - defaults/win-64::navigator-updater==0.3.0=py39haa95532_0
  - defaults/noarch::nbclassic==0.3.5=pyhd3eb1b0_0
  - defaults/win-64::nbclient==0.5.13=py39haa95532_0
  - defaults/win-64::nbconvert==6.4.4=py39haa95532_0
  - defaults/win-64::nbformat==5.5.0=py39haa95532_0
  - defaults/win-64::nest-asyncio==1.5.5=py39haa95532_0
  - defaults/win-64::networkx==2.8.4=py39haa95532_0
  - defaults/noarch::nltk==3.7=pyhd3eb1b0_0
  - defaults/noarch::nose==1.3.7=pyhd3eb1b0_1008
  - defaults/win-64::notebook==6.4.12=py39haa95532_0
  - defaults/win-64::numba==0.55.1=py39hf11a4ad_0
  - defaults/win-64::numexpr==2.8.3=py39hb80d3ca_0
  - defaults/win-64::numpy==1.21.5=py39h7a0a035_3
  - defaults/win-64::numpy-base==1.21.5=py39hca35cd5_3
  - defaults/win-64::numpydoc==1.4.0=py39haa
done

==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 24.3.0

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: C:\Users\oucwj\anaconda3

  added / updated specs:
    - wrf-python

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _anaconda_depends-2022.10  |           py39_2          68 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    anaconda-custom            |           py39_2          13 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    ca-certificates-2024.2.2   |       h56e8100_0         152 KB  conda-forge
    m2w64-gcc-libgfortran-5.3.0|                6         342 KB  conda-forge
    m2w64-gcc-libs-5.3.0       |                7         520 KB  conda-forge
    m2w64-gcc-libs-core-5.3.0  |                7         214 KB  conda-forge
    m2w64-gmp-6.1.0            |                2         726 KB  conda-forge
    openssl-1.1.1q             |       h8ffe710_0         5.8 MB  conda-forge
    python_abi-3.9             |           2_cp39           4 KB  conda-forge
    setuptools-69.5.1          |     pyhd8ed1ab_0         490 KB  conda-forge
    wrf-python-1.3.4.1         |   py39h412d2f7_2         5.3 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        13.5 MB

The following NEW packages will be INSTALLED:

  _anaconda_depends  anaconda/pkgs/main/win-64::_anaconda_depends-2022.10-py39_2 None
  m2w64-gcc-libgfor~ conda-forge/win-64::m2w64-gcc-libgfortran-5.3.0-6 None
  m2w64-gcc-libs     conda-forge/win-64::m2w64-gcc-libs-5.3.0-7 None
  m2w64-gcc-libs-co~ conda-forge/win-64::m2w64-gcc-libs-core-5.3.0-7 None
  m2w64-gmp          conda-forge/win-64::m2w64-gmp-6.1.0-2 None
  python_abi         conda-forge/win-64::python_abi-3.9-2_cp39 None
  setuptools         conda-forge/noarch::setuptools-69.5.1-pyhd8ed1ab_0 None
  wrf-python         conda-forge/win-64::wrf-python-1.3.4.1-py39h412d2f7_2 None

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2022.07.19~ --> conda-forge::ca-certificates-2024.2.2-h56e8100_0 None

The following packages will be SUPERSEDED by a higher-priority channel:

  anaconda               pkgs/main::anaconda-2022.10-py39_0 --> anaconda/pkgs/main::anaconda-custom-py39_2 None
  openssl              pkgs/main::openssl-1.1.1q-h2bbff1b_0 --> conda-forge::openssl-1.1.1q-h8ffe710_0 None

Proceed ([y]/n)? y

Downloading and Extracting Packages
m2w64-gmp-6.1.0      | 726 KB    | ########################################################################################################################################################################## | 100%  
wrf-python-1.3.4.1   | 5.3 MB    | ########################################################################################################################################################################## | 100%  
m2w64-gcc-libgfortra | 342 KB    | ########################################################################################################################################################################## | 100%  
openssl-1.1.1q       | 5.8 MB    | ########################################################################################################################################################################## | 100%  
python_abi-3.9       | 4 KB      | ########################################################################################################################################################################## | 100%  
setuptools-69.5.1    | 490 KB    | ########################################################################################################################################################################## | 100%  
_anaconda_depends-20 | 68 KB     | ########################################################################################################################################################################## | 100%  
m2w64-gcc-libs-core- | 214 KB    | ########################################################################################################################################################################## | 100%  
m2w64-gcc-libs-5.3.0 | 520 KB    | ########################################################################################################################################################################## | 100%  
ca-certificates-2024 | 152 KB    | ########################################################################################################################################################################## | 100%  
Preparing transaction: done
Verifying transaction: failed

RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
conda's operating environment.`

**Comment by kafitzgerald** [comment]
It looks like you may be having some trouble mixing packages from the "defaults" and "conda-forge" channels.  

You might try installing wrf-python in a new environment using packages only from "conda-forge".

```
conda create -n wrf -c conda-forge wrf-python
conda activate wrf
```

If you need additional packages in this environment, you'll want to try to install them from "conda-forge" as well if possible.

**Comment by OMGTaylor0814** [comment]
Dear @kafitzgerald ,
Thanks so much! It worked and I can use it now~
