### ISSUE TITLE
WRF-Python Install - Mac M2 Max

### ISSUE THREAD

**Issue by sudesokin** [NCAR/wrf-python#249]
Hello @erogluorhan 
When will wrf-python be compatible with M chips?
I would be very happy if you could give me some information.
Thank you

**Comment by erogluorhan** [comment]
Hi @sudesokin , thanks a lot for opening this issue! I'd suggest reading the issues #235 and #148 that have some context about the situation. I will close this to avoid duplicate issues; please feel free to join the discussion in the other issues.
