### ISSUE TITLE
Are there any routines for regridding?

### ISSUE THREAD

**Issue by anikfal** [NCAR/wrf-python#257]
It seems there are no available routines similar to NCL's [`rgrid2rcm`](https://www.ncl.ucar.edu/Document/Functions/Built-in/rgrid2rcm.shtml) for regridding from a rectilinear lat/lon grid to a curvilinear grid.

Is this supposed to be handled by other available Python modules (e.g., xESMF)?

**Comment by kafitzgerald** [comment]
Thanks for the question!

I'd suggest exploring xESMF and/or other regridding packages.  As you noted, this isn't something currently covered by WRF-Python and active development here isn't a high priority at the moment.

However, we are working on some additional NCL transition resources and guidance over on [GeoCAT-applications](https://github.com/NCAR/geocat-applications) and regridding is high on the "todo" list there.  Feedback on what types of transition resources might be helpful and/or specific gaps in the current ecosystem of scientific python packages (as compared to NCL) would be very welcome in issues / discussions over on that repo or feel free to reach out directly to the [GeoCAT team](https://geocat.ucar.edu/).
