### ISSUE TITLE
T_BASE=300

### ISSUE THREAD

**Issue by saneku** [NCAR/wrf-python#27]
Hello!
I was wondering, why T_BASE=300 K?

May be it should depend on what is in the namelist.base_temp=290 (which is in my case) ?
Or I wrong?
Thank you!

**Comment by bladwig1** [comment]
T+300 is the correct way to get potential temperature. This question has
been asked to WRF users group in the past, and here is the thread:

http://mailman.ucar.edu/pipermail/wrf-users/2013/003117.html

Regards,

Bill

**Comment by saneku** [comment]
ok
thanks!

**Comment by saneku** [comment]
ok
thanks!

**Comment by bladwig1** [comment]
For the official reference in the WRF User Manual, here is a link:

http://www2.mmm.ucar.edu/wrf/users/docs/user_guide_V3.9/users_guide_chap5.htm#fields

Scroll to the bottom for the section labeled "Special WRF Output Variables".
