### ISSUE TITLE
interpline/vinterp: Show warning if latlon=True but field{2,3}d.coords is None

### ISSUE THREAD

**Issue by hanschen** [NCAR/wrf-python#38]
`interpline` and `vinterp` have an option `latlon` to return the interpolated latitude and longitude coordinates along the line. However, if the input field (`field2d` or `field3d`) doesn't contain information about the lat/lon coordinates, e.g. if it's a regular numpy array, the functions will silently fail to provide the interpolated lat/lon, which can be confusing.

It would be nice if the functions could alert the user when `latlon=True` but `latlon_coordvars(field{2,3}d.coords)` returns None. I don't know what the best way is to show this warning though, otherwise I would be willing to provide a Pull Request.

**Comment by bladwig1** [comment]
Yes, this is probably a good idea.  I'll just throw it as a UserWarning.  It's an easy enough request that I can just add it as part of the upcoming 1.1 release.

**Comment by hanschen** [comment]
Thanks!
