### ISSUE TITLE
Having an issue plotting different variables from the diagnostic table

### ISSUE THREAD

**Issue by mstewart2150** [NCAR/wrf-python#43]
I am trying to use the example found [here](http://wrf-python.readthedocs.io/en/latest/plot.html#id1) to plot temperature in my domain. The table of diagnostics says I can slide in "temp", but I am having an error and am not sure what it wants, much less a solution. (I just replaced "slp" in the sample code for "temp", just to test this whole thing out)
``from netCDF4 import Dataset``
``import matplotlib.pyplot as plt
``from matplotlib.cm import get_cmap
``from mpl_toolkits.basemap import Basemap

``from wrf import to_np, getvar, smooth2d, get_basemap, latlon_coords

``# Open the NetCDF file
``ncfile = Dataset("X:\WRF\AUG2022\Domain1\wrfout_d01_2017-08-20_12%3A30%3A00")``

``# Get the sea level pressure``
``slp = getvar(ncfile, "temp")``

``# Smooth the sea level pressure since it tends to be noisy near the mountains``
``smooth_slp = smooth2d(slp, 3)``

``# Get the latitude and longitude points``
``lats, lons = latlon_coords(slp)``

``# Get the basemap object``
``bm = get_basemap(slp)``

``# Create a figure``
``fig = plt.figure(figsize=(12,9))``

``# Add geographic outlines``
``bm.drawcoastlines(linewidth=0.25)``
``bm.drawstates(linewidth=0.25)``
``bm.drawcountries(linewidth=0.25)``

``# Convert the lats and lons to x and y.  Make sure you convert the lats and lons to``
``# numpy arrays via to_np, or basemap crashes with an undefined RuntimeError.``
``x, y = bm(to_np(lons), to_np(lats))``

``# Draw the contours and filled contours``
``bm.contour(x, y, to_np(smooth_slp), 10, colors="black")``
``bm.contourf(x, y, to_np(smooth_slp), 10, cmap=get_cmap("jet"))``

``# Add a color bar``
``plt.colorbar(shrink=.62)``

``plt.title("Sea Level Pressure (hPa)")``

``plt.show()``

This is my error:
``---------------------------------------------------------------------------``
``TypeError                                 Traceback (most recent call last)``
``<ipython-input-7-ba6c6362d2a8> in <module>()``
``    34 ``
``     35 # Draw the contours and filled contours``
``---> 36 bm.contour(x, y, to_np(smooth_slp), 10, colors="black")``
``     37 bm.contourf(x, y, to_np(smooth_slp), 10, cmap=get_cmap("jet"))``
``     38 ``
``
``C:\Users\Michael\Anaconda3\envs\wrf\lib\site-packages\mpl_toolkits\basemap\__init__.pyc in`` ``with_transform(self, x, y, data, *args, **kwargs)``
``    519             # convert lat/lon coords to map projection coords.``
``    520             x, y = self(x,y)``
``--> 521         return plotfunc(self,x,y,data,*args,**kwargs)``
``    522     return with_transform``
``    523 ``
``
``C:\Users\Michael\Anaconda3\envs\wrf\lib\site-packages\mpl_toolkits\basemap\__init__.pyc in`` ``contour(self, x, y, data, *args, **kwargs)``
``   3566                 mask = np.logical_or(ma.getmaskarray(data),xymask)``
``  3567                 data = ma.masked_array(data,mask=mask)``
``-> 3568                 CS = ax.contour(x,y,data,*args,**kwargs)``
``   3569         except:``
``   3570             ax.hold(b)``
````
``C:\Users\Michael\Anaconda3\envs\wrf\lib\site-packages\matplotlib\__init__.pyc in inner(ax, *args,`` ``**kwargs)``
``   1817                     warnings.warn(msg % (label_namer, func.__name__),``
``   1818                                   RuntimeWarning, stacklevel=2)``
``-> 1819             return func(ax, *args, **kwargs)``
``   1820         pre_doc = inner.__doc__``
``   1821         if pre_doc is None:``
``
``C:\Users\Michael\Anaconda3\envs\wrf\lib\site-packages\matplotlib\axes\_axes.pyc in contour(self,`` ``*args, **kwargs)``
``   5617             self.cla()``
``   5618         kwargs['filled'] = False``
``-> 5619         return mcontour.QuadContourSet(self, *args, **kwargs)``
``   5620     contour.__doc__ = mcontour.QuadContourSet.contour_doc``
``   5621 ``
``
``C:\Users\Michael\Anaconda3\envs\wrf\lib\site-packages\matplotlib\contour.pyc in __init__(self, ax,`` ``*args, **kwargs)``
``   1422         are described in QuadContourSet.contour_doc.``
``   1423         """
``-> 1424         ContourSet.__init__(self, ax, *args, **kwargs)``
``   1425 ``
``   1426     def _process_args(self, *args, **kwargs):``

``C:\Users\Michael\Anaconda3\envs\wrf\lib\site-packages\matplotlib\contour.pyc in __init__(self, ax,`` ``*args, **kwargs)``
``    861         self._transform = kwargs.get('transform', None)``
``    862 ``
``--> 863         self._process_args(*args, **kwargs)``
``    864         self._process_levels()``
``    865 ``
````
``C:\Users\Michael\Anaconda3\envs\wrf\lib\site-packages\matplotlib\contour.pyc in _process_args(self,`` ``*args, **kwargs)``
``   1443                 self._corner_mask = mpl.rcParams['contour.corner_mask']``
``   1444 ``
``-> 1445             x, y, z = self._contour_args(args, kwargs)``
``   1446 ``
``   1447             _mask = ma.getmask(z)``
``
``C:\Users\Michael\Anaconda3\envs\wrf\lib\site-packages\matplotlib\contour.pyc in _contour_args(self,`` ``args, kwargs)``
``   1526             args = args[1:]``
``   1527         elif Nargs <= 4:``
``-> 1528             x, y, z = self._check_xyz(args[:3], kwargs)``
``   1529             args = args[3:]``
``   1530         else:``
````
``C:\Users\Michael\Anaconda3\envs\wrf\lib\site-packages\matplotlib\contour.pyc in _check_xyz(self,`` ``args, kwargs)``
``   1560 ``
``   1561         if z.ndim != 2:``
``-> 1562             raise TypeError("Input z must be a 2D array.")``
``   1563         else:``
``   1564             Ny, Nx = z.shape``
``
``TypeError: Input z must be a 2D array.```

Thank you so much in advance.

**Comment by mstewart2150** [comment]
I am so sorry for the formatting of this code...I'm very new here.

**Comment by bladwig1** [comment]
When you copied the example for SLP and then changed the product type to "temp", you're now getting back a 3-dimensional variable instead of a 2-dimensional variable.  Matplotlib does not know how to contour a 3-dimensional variable, which is what the error is indicating.  So, you must either extract a 2-dimensional variable using a fixed value for bottom_top (e.g. bottom_top=0 for surface level), or you must interpolate the 3-dimensional "temp" variable to a standard meteorological level using the interplevel function.

To get the lowest temp level:

> temp = getvar(ncfile, "temp") # This is a 3D variable
   lowest_temp = temp[0,...] # This is a 2D variable

To get the 750 hPa temps:

> temp = getvar(ncfile, "temp")
   pres = getvar(ncfile, "pressure")
   temp_750 = interplevel(temp, pres, 750.)

You should now be able to contour either of the above arrays.  

Hope this helps, 

Bill

**Comment by mstewart2150** [comment]
This was a perfect explanation and solution. Thank you so much!
