### ISSUE TITLE
Custom vertical dimension in vinterp

### ISSUE THREAD

**Issue by honnorat** [NCAR/wrf-python#54]
Hello,

It would be nice to allow [`wrf.vinterp()`](https://github.com/NCAR/wrf-python/blob/develop/src/wrf/interp.py#L464) use a custom name for the vertical dimension it creates. Currently, it is called `interp_level` and cannot be changed.

This would allow the interpolation along an existing coordinate variable, or along different vertical axes.

Example:
```python
from netCDF4 import Dataset
import wrf
nc = Dataset("test/ci_tests/ci_test_file.nc")
tk = wrf.getvar(ncfile, "tk")
levels = [925, 850, 750, 500]

tkp_def = wrf.vinterp(nc, field=tk, vert_coord="pressure", interp_levels=levels)
tkp_new = wrf.vinterp(nc, field=tk, vert_coord="pressure", interp_levels=levels, vdim_name="p_levels")
print("default:", tkp_def.dims)
print("named dim:", tkp_new.dims)
```
result:
```
default: ('interp_level', 'south_north', 'west_east')
named dim: ('p_levels', 'south_north', 'west_east')
```

**Comment by bladwig1** [comment]
You can change coordinate names using xarray's DataArray.rename() function.
