### ISSUE TITLE
No raise a warning or error when using a keyword not in getvar function

### ISSUE THREAD

**Issue by bugsuse** [NCAR/wrf-python#63]
I get the wind field data for time index 0 when I extract data from wrfout using getvar(wrfin, 'U10', timeindex=1), it's just because getvar accept keyword timeidx not timeindex, but without raise warning or error using timeindex.  So is it better that raise a warning or error when using a keyword not accept by function?

**Comment by bladwig1** [comment]
This is a bug. 

(Note: This only occurs when extracting variables in the NetCDF files, not when computing diagnostics)

**Comment by bugsuse** [comment]
Well, I will take care of it. Thank you so much!
