### ISSUE TITLE
storm relative helicity calculation incorrect for southern hemisphere

### ISSUE THREAD

**Issue by swnesbitt** [NCAR/wrf-python#69]
In the fortran code ported from NCL to calculate storm relative helicity, the code should have a different formula depending on whether the point is in the northern or southern hemisphere.  The 'left moving' supercell storm motion should be considered, not the 'right mover' as in the Northern Hemisphere.

Line 103 of [blob/develop/fortran/wrf_relhl.f90](https://github.com/NCAR/wrf-python/blob/develop/fortran/wrf_relhl.f90)

`            bdr = adr + 30.D0`

Should be

`            bdr = adr - 30.D0`

in the Southern Hemisphere.  This is a bug in NCL also.

I am not sure the best way to handle this issue, since latitude is not passed into the code.  Should it be an optional flag?

**Comment by bladwig1** [comment]
Yeah, it's going to need a flag for the raw computation, then the extraction routine in python can pull out the latitudes to determine hemisphere (or some other means).

Thanks for the report.

**Comment by bladwig1** [comment]
@swnesbitt Do you have a WRF file in the southern hemisphere that I can use to test this? If you have access to Cheyenne, you can just send me the path.  Otherwise, you can follow the instructions here to FTP it: https://wrf-python.readthedocs.io/en/latest/support.html#submitting-files

**Comment by swnesbitt** [comment]
We put a file here /gpfs/u/home/jmulhol2

**Comment by bladwig1** [comment]
Got it, thanks!

You can see the before and after below. 

![srhel_before](https://user-images.githubusercontent.com/17321532/46893019-b7a92a80-ce2c-11e8-977a-b8225c222389.png)
![srhel_after](https://user-images.githubusercontent.com/17321532/46893039-cabbfa80-ce2c-11e8-9e11-13a80566be75.png)
