### ISSUE TITLE
vinterp fails to do extrapolation

### ISSUE THREAD

**Issue by ericmet** [NCAR/wrf-python#79]
I was trying to vertically interpolate my WRF output to pressure levels. My WRF simulation includes some islands, such that the largest height at the lowest model level is 2625 m.

As the 1st step, I tested vinterp, by interpolating the height field to some selected pressure levels:
ht=getvar(dataset,"height",units="m")
levels=[1000,850,500,200]
ht_int=vinterp(dataset,ht,'p',levels,extrapolate=True)

So, ht_int[0, : , : ] is the interpolated height value at the 1000 hPa level. And, I expected that the values range from -50 to 50 m. However, it turns out that, the maximum value of ht_int[0, : , :] is still 2625 m, the same as the largest value at the lowest model level. The minimum value is about 30 m.

I repeated the vinterp with the extrapolate=False, I got the same results. It seems that the code does not do extrapolation to give levels below ground even with extrapolate=True.

For ht_int[2, : , : ] (the interpolated value at the 500 hPa level), I got the expected result.

**Comment by ericmet** [comment]
I think I have figured out the reason. The parameter _field_type_ is optional, and by default it is 'None'. This yields _icase=0_.
However, as per the wrf_vintrp.f90, extrapolation is only arranged for _icase>0_. That's why the field is not extrapolated even with _extrapolate=True_.
I tried that with _extrapolate=True_ and _field_type='ght'_ (_icase=2_), I got reasonable extrapolated results.

Hence, I suggest to add more description in the handbook to remind users that field_type should be specified if they want to extrapolate the pressure, height, temperature, potential temperature or equivalent potential temperature field.

**Comment by bladwig1** [comment]
That's correct. The only time that extrapolation is performed is for the special cases where your field is height and your vertical coordinate is pressure, or your field is pressure and your vertical coordinate is height. It uses standard atmosphere to do the extrapolation. In any other situation, the lowest model level is used. The documentation had already been updated a bit when #74 was fixed (currently in develop branch), but it still needs some work, so I'll keep this issue open until I check in the doc improvements. Thanks!
